### ISSUE TITLE
【功能需求】实时字幕支持

### ISSUE THREAD

**Issue by mofanx** [H1DDENADM1N/CapsWriter-Offline#36]
改用sensevoice模型后，支持的语言更加丰富了，速度也更快了，咱们是不是可以在原有基础上，再增加一个实时字幕的功能模块？感觉大部分工作是现成的，调整下文字输出和显示的方式，就能实现非常好的实时字幕效果！

@H1DDENADM1N 大佬，有没有兴趣搞一下子😁

**Comment by H1DDENADM1N** [comment]
TMSpeech是个好项目，但我并没有实时字幕的需求，暂时不考虑加进去。我周末看看他的源码，如果不复杂可出个分支。

**Comment by mofanx** [comment]
@H1DDENADM1N 感谢大佬！我也是看到了TMSpeech这个项目，但是发现目前模型识别的效果还有提升的空间，想更换sensevoice模型不是太方便，所以才联想到通过capswriter来实现。如果真的增加上实时字幕，再加上原有的语音输入、文本转录、字幕生成、语音翻译等功能，感觉对个人来说，就是一个比较完整的语音解决方案了。😆

**Comment by H1DDENADM1N** [comment]
可惜TMSpeech不是python不能直接抄，看周末有没有时间肝出来

**Comment by mofanx** [comment]
大佬威武👍👍

**Comment by H1DDENADM1N** [comment]
我在api4sensevoice寻找到了实时字幕的体验 https://github.com/H1DDENADM1N/api4sensevoice 配合voicemeeter软件实现只录内音不录麦克风音，浏览器窗口透明度调节由SmartSystemMenu软件实现。

![web_client](https://github.com/user-attachments/assets/02bad12a-ea33-4425-a20b-02a8bbb0224d)


![Cooperate with Voicemeeter to record internal voice](https://github.com/user-attachments/assets/b359da8d-4f6e-484f-bde3-4654b87868d5)

**Comment by mofanx** [comment]
不知道为啥，一直提示我模型不存在😅
```
py server_wss.py
Key Conformer already exists in model_classes, re-register
Key Linear already exists in adaptor_classes, re-register
Key TransformerDecoder already exists in decoder_classes, re-register
Key LightweightConvolutionTransformerDecoder already exists in decoder_classes, re-register
Key LightweightConvolution2DTransformerDecoder already exists in decoder_classes, re-register
Key DynamicConvolutionTransformerDecoder already exists in decoder_classes, re-register
Key DynamicConvolution2DTransformerDecoder already exists in decoder_classes, re-register
2024-11-03 10:46:36,991 - modelscope - ERROR - The request model: ./models/speech_eres2net_large_sv_zh-cn_3dspeaker_16k does not exist!
Traceback (most recent call last):
  File "E:\protable\msys64\home\Yan\python\api4sensevoice\venv\Lib\site-packages\modelscope\pipelines\util.py", line 35, in is_official_hub_impl
    _ = HubApi().get_model(path, revision=revision)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\protable\msys64\home\Yan\python\api4sensevoice\venv\Lib\site-packages\modelscope\hub\api.py", line 238, in get_model
    handle_http_response(r, logger, cookies, model_id)
  File "E:\protable\msys64\home\Yan\python\api4sensevoice\venv\Lib\site-packages\modelscope\hub\errors.py", line 118, in handle_http_response
    raise HTTPError(http_error_msg, response=response)
requests.exceptions.HTTPError: The request model: ./models/speech_eres2net_large_sv_zh-cn_3dspeaker_16k does not exist!

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\protable\msys64\home\Yan\python\api4sensevoice\server_wss.py", line 160, in <module>
    sv_pipeline = pipeline(
                  ^^^^^^^^^
  File "E:\protable\msys64\home\Yan\python\api4sensevoice\venv\Lib\site-packages\modelscope\pipelines\builder.py", line 118, in pipeline
    model = normalize_model_input(
            ^^^^^^^^^^^^^^^^^^^^^^
  File "E:\protable\msys64\home\Yan\python\api4sensevoice\venv\Lib\site-packages\modelscope\pipelines\builder.py", line 29, in normalize_model_input
    if isinstance(model, str) and is_official_hub_path(model, model_revision):
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\protable\msys64\home\Yan\python\api4sensevoice\venv\Lib\site-packages\modelscope\pipelines\util.py", line 41, in is_official_hub_path
    return is_official_hub_impl(path)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\protable\msys64\home\Yan\python\api4sensevoice\venv\Lib\site-packages\modelscope\pipelines\util.py", line 38, in is_official_hub_impl
    raise ValueError(f'invalid model repo path {e}')
ValueError: invalid model repo path The request model: ./models/speech_eres2net_large_sv_zh-cn_3dspeaker_16k does not exist!
```

**Comment by H1DDENADM1N** [comment]
> 不知道为啥，一直提示我模型不存在😅

我这边直连魔塔下载缓慢，所以挂代理手动下载然后指定的路径以使用的本地模型。你需要改回原版模型路径，它监测到没有模型文件会自动去魔塔下载。或是也修改到正确的模型路径

https://github.com/H1DDENADM1N/api4sensevoice/commit/2827bf71e26ce933c65b99f5341d5bbc50b9d5c0

**Comment by mofanx** [comment]
原来如此，我说怎么只下载了SenseVoiceSmall模型，然后搜索另外的模型名称又没有搜索到了😁

**Comment by mofanx** [comment]
晚上体验了一下这个项目，可能因为字幕是整句识别完成后输出的，所以感官上延迟感比较明显，个人觉得还是[TMSpeech](https://github.com/jxlpzqc/TMSpeech)那种浮动字幕实时呈现的方式更加符合用户习惯。Capswirter要通过sensevoice实现类似的体验，可能也不太容易。🤣

**Comment by quifas** [comment]
实时输出有计划搞么？
