### ISSUE TITLE
right shift作为speech_recognition_shortcut，提示错误。

### ISSUE THREAD

**Issue by bushnerd** [H1DDENADM1N/CapsWriter-Offline#38]
```
rror in keyboard hook:
Traceback (most recent call last):
File "D:\Programs\CapsWriter-Offline-GUI-v1.3.1\site-packages\keyboard\_winkeyboard.py", line 541, in low_level_keyboard_handler
should_continue = process_key(event_type, vk, scan_code, is_extended)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "D:\Programs\CapsWriter-Offline-GUI-v1.3.1\site-packages\keyboard\_winkeyboard.py", line 529, in process_key
return callback(KeyboardEvent(event_type=event_type, scan_code=scan_code or -vk, name=name, is_keypad=is_keypad))
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "D:\Programs\CapsWriter-Offline-GUI-v1.3.1\site-packages\keyboard\__init__.py", line 254, in direct_callback
if not key_hook(event):
^^^^^^^^^^^^^^^
File "D:\Programs\CapsWriter-Offline-GUI-v1.3.1\util\client_shortcut_handler.py", line 241, in hold_handler
hold_mode(e)
File "D:\Programs\CapsWriter-Offline-GUI-v1.3.1\util\client_shortcut_handler.py", line 211, in hold_mode
launch_task()
File "D:\Programs\CapsWriter-Offline-GUI-v1.3.1\util\client_shortcut_handler.py", line 48, in launch_task
if keyboard.is_pressed(Config.offline_translate_shortcut):
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "D:\Programs\CapsWriter-Offline-GUI-v1.3.1\site-packages\keyboard\__init__.py", line 417, in is_pressed
steps = parse_hotkey(hotkey)
^^^^^^^^^^^^^^^^^^^^
File "D:\Programs\CapsWriter-Offline-GUI-v1.3.1\site-packages\keyboard\__init__.py", line 358, in parse_hotkey
steps.append(tuple(key_to_scan_codes(key) for key in keys))
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "D:\Programs\CapsWriter-Offline-GUI-v1.3.1\site-packages\keyboard\__init__.py", line 358, in <genexpr>
steps.append(tuple(key_to_scan_codes(key) for key in keys))
^^^^^^^^^^^^^^^^^^^^^^
File "D:\Programs\CapsWriter-Offline-GUI-v1.3.1\site-packages\keyboard\__init__.py", line 309, in key_to_scan_codes
normalized = normalize_name(key)
^^^^^^^^^^^^^^^^^^^
File "D:\Programs\CapsWriter-Offline-GUI-v1.3.1\site-packages\keyboard\_canonical_names.py", line 1239, in normalize_name
raise ValueError('Can only normalize non-empty string names. Unexpected '+ repr(name))
ValueError: Can only normalize non-empty string names. Unexpected ''
Error in keyboard hook:
Traceback (most recent call last):
File "D:\Programs\CapsWriter-Offline-GUI-v1.3.1\site-packages\keyboard\_winkeyboard.py", line 541, in low_level_keyboard_handler
should_continue = process_key(event_type, vk, scan_code, is_extended)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "D:\Programs\CapsWriter-Offline-GUI-v1.3.1\site-packages\keyboard\_winkeyboard.py", line 529, in process_key
return callback(KeyboardEvent(event_type=event_type, scan_code=scan_code or -vk, name=name, is_keypad=is_keypad))
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "D:\Programs\CapsWriter-Offline-GUI-v1.3.1\site-packages\keyboard\__init__.py", line 254, in direct_callback
if not key_hook(event):
^^^^^^^^^^^^^^^
File "D:\Programs\CapsWriter-Offline-GUI-v1.3.1\util\client_shortcut_handler.py", line 241, in hold_handler
hold_mode(e)
File "D:\Programs\CapsWriter-Offline-GUI-v1.3.1\util\client_shortcut_handler.py", line 211, in hold_mode
launch_task()
File "D:\Programs\CapsWriter-Offline-GUI-v1.3.1\util\client_shortcut_handler.py", line 48, in launch_task
if keyboard.is_pressed(Config.offline_translate_shortcut):
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "D:\Programs\CapsWriter-Offline-GUI-v1.3.1\site-packages\keyboard\__init__.py", line 417, in is_pressed
steps = parse_hotkey(hotkey)
^^^^^^^^^^^^^^^^^^^^
File "D:\Programs\CapsWriter-Offline-GUI-v1.3.1\site-packages\keyboard\__init__.py", line 358, in parse_hotkey
steps.append(tuple(key_to_scan_codes(key) for key in keys))
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "D:\Programs\CapsWriter-Offline-GUI-v1.3.1\site-packages\keyboard\__init__.py", line 358, in <genexpr>
steps.append(tuple(key_to_scan_codes(key) for key in keys))
^^^^^^^^^^^^^^^^^^^^^^
File "D:\Programs\CapsWriter-Offline-GUI-v1.3.1\site-packages\keyboard\__init__.py", line 309, in key_to_scan_codes
normalized = normalize_name(key)
^^^^^^^^^^^^^^^^^^^
File "D:\Programs\CapsWriter-Offline-GUI-v1.3.1\site-packages\keyboard\_canonical_names.py", line 1239, in normalize_name
raise ValueError('Can only normalize non-empty string names. Unexpected '+ repr(name))
ValueError: Can only normalize non-empty string names. Unexpected ''
```

**Comment by H1DDENADM1N** [comment]
right shift默认已用做在线翻译辅助键，需要同步修改`online_translate_shortcut   = 'right shift'` 改为其他不同按键。
